--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Faizx511x/Specter-MP4
build-by-default: true
branches:
- master
projects:
  Specter-MP4:
    path: ""
    icon: "resources/specter.jpg"
...
