name: Specter
version: "0.9"
author: Falkirks
main: specter\Specter
api: 4.0.0
commands:
  specter:
    usage: /specter <action> <player> [params]
    permission: specter.command
    aliases: ['s']
    
permissions:
  specter:
    default: op
  specter.command:
    default: op
