name: Specter
version: 0.4
author: Falkirks
main: specter\Specter
api: [1.13.0, 2.0.0]
softdepend: ["iControlU"]
commands:
  specter:
    usage: /specter <action> <player> [params]
    permission: specter.command
    aliases: ['s']
permissions:
  specter:
    default: op
    children:
      specter.command:
        default: op
