<?php
namespace specter\network;

use pocketmine\math\Vector3;
use pocketmine\network\mcpe\protocol\DataPacket;
use pocketmine\network\SourceInterface;
use pocketmine\Player;

class SpecterPlayer extends Player{
    public $spec_needRespawn = false;
    public function __construct(SourceInterface $interface, $clientID, $ip, $port){
        parent::__construct($interface, $clientID, $ip, $port); // TODO: Change the autogenerated stub
    }

    public function dataPacket(DataPacket $packet, $needACK = false){
        return parent::dataPacket($packet, $needACK); // TODO: Change the autogenerated stub
    }

    public function handleDataPacket(DataPacket $packet){
        parent::handleDataPacket($packet); // TODO: Change the autogenerated stub
    }

    protected function sendNextChunk(){
        parent::sendNextChunk();
    }

    protected function completeLoginSequence(){
        parent::completeLoginSequence();
    }

    /**
     * @return Vector3
     */
    public function getForceMovement(){
        return $this->forceMovement;
    }

}