<?php
namespace specter\network;

use pocketmine\entity\Skin;
use pocketmine\network\mcpe\protocol\BatchPacket;
use pocketmine\network\mcpe\protocol\DataPacket;
use pocketmine\network\mcpe\protocol\LoginPacket;
use pocketmine\network\mcpe\protocol\MovePlayerPacket;
use pocketmine\network\mcpe\protocol\PacketPool;
use pocketmine\network\mcpe\protocol\PlayStatusPacket;
use pocketmine\network\mcpe\protocol\ProtocolInfo;
use pocketmine\network\mcpe\protocol\RequestChunkRadiusPacket;
use pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket;
use pocketmine\network\mcpe\protocol\ResourcePacksInfoPacket;
use pocketmine\network\mcpe\protocol\RespawnPacket;
use pocketmine\network\mcpe\protocol\SetHealthPacket;
use pocketmine\network\mcpe\protocol\StartGamePacket;
use pocketmine\network\mcpe\protocol\TextPacket;
use pocketmine\network\SourceInterface;
use pocketmine\Player;
use pocketmine\utils\BinaryStream;
use pocketmine\utils\TextFormat;
use pocketmine\utils\UUID;
use specter\Specter;

class SpecterInterface implements SourceInterface{
    /** @var  SpecterPlayer[]|\SplObjectStorage */
    private $sessions;
    /** @var  Specter */
    private $specter;
    /** @var  array */
    private $ackStore;
    /** @var  array */
    private $replyStore;
    public function __construct(Specter $specter){
        $this->specter = $specter;
        $this->sessions = new \SplObjectStorage();
        $this->ackStore = [];
        $this->replyStore = [];
    }

    public function start(){
        //NOOP
    }

    /**
     * Sends a DataPacket to the interface, returns an unique identifier for the packet if $needACK is true
     *
     * @param Player $player
     * @param DataPacket $packet
     * @param bool $needACK
     * @param bool $immediate
     *
     * @return int
     */
    public function putPacket(Player $player, DataPacket $packet, bool $needACK = false, bool $immediate = true){
        if($player instanceof SpecterPlayer) {
            //$this->specter->getLogger()->info(get_class($packet));
            switch (get_class($packet)){
                case ResourcePacksInfoPacket::class:
                    $pk = new ResourcePackClientResponsePacket();
                    $pk->status = ResourcePackClientResponsePacket::STATUS_COMPLETED;
                    $pk->handle($player->getSessionAdapter());
                    break;
                case TextPacket::class:
                	/** @var TextPacket $packet */
                    $type = "Unknown";
                    switch($packet->type){
                        case TextPacket::TYPE_CHAT:
                            $type = "Chat"; // warn about deprecation?
                            break;
                        case TextPacket::TYPE_RAW:
                            $type = "Message";
                            break;
                        case TextPacket::TYPE_POPUP:
                            $type = "Popup";
                            break;
                        case TextPacket::TYPE_TIP:
                            $type = "Tip";
                            break;
                        case TextPacket::TYPE_TRANSLATION:
                            $type = "Translation (with params: " . implode(", ", $packet->parameters) . ")";
                            break;
                    }
                    $this->specter->getLogger()->info(TextFormat::LIGHT_PURPLE . "$type to {$player->getName()}: " . TextFormat::WHITE . $packet->message);
                    break;
                case SetHealthPacket::class:
                	/** @var SetHealthPacket $packet */
                    if($packet->health <= 0){
                        if($this->specter->getConfig()->get("autoRespawn")){
                            $pk = new RespawnPacket();
                            $this->replyStore[$player->getName()][] = $pk;
                        }
                    }
                    else{
                        $player->spec_needRespawn = true;
                    }
                    break;
                case StartGamePacket::class:
                    $pk = new RequestChunkRadiusPacket();
                    $pk->radius = 8;
                    $this->replyStore[$player->getName()][] = $pk;
                    break;
                case PlayStatusPacket::class:
                	/** @var PlayStatusPacket $packet */
                    switch ($packet->status){
                        case PlayStatusPacket::PLAYER_SPAWN:
                            /*$pk = new MovePlayerPacket();
                            $pk->x = $player->getPosition()->x;
                            $pk->y = $player->getPosition()->y;
                            $pk->z = $player->getPosition()->z;
                            $pk->yaw = $player->getYaw();
                            $pk->pitch = $player->getPitch();
                            $pk->bodyYaw = $player->getYaw();
                            $pk->onGround = true;
                            $pk->handle($player);*/
                            break;
                    }
                    break;
                case MovePlayerPacket::class:
                	/** @var MovePlayerPacket $packet */
                    $eid = $packet->entityRuntimeId;
                    if($eid === $player->getId() && $player->isAlive() && $player->spawned === true && $player->getForceMovement() !== null) {
                        $packet->mode = MovePlayerPacket::MODE_NORMAL;
                        $packet->yaw += 25; //FIXME little hacky
                        $this->replyStore[$player->getName()][] = $packet;
                    }
                    break;
                case BatchPacket::class:
                	/** @var BatchPacket $packet */
                    $packet->offset = 1;
                    $packet->decode();

                    foreach($packet->getPackets() as $buf){
                        $pk = PacketPool::getPacketById(ord($buf{0}));
                        //$this->specter->getLogger()->info("PACK:" . get_class($pk));
                        if(!$pk->canBeBatched()){
                            throw new \InvalidArgumentException("Received invalid " . get_class($pk) . " inside BatchPacket");
                        }

                        $pk->setBuffer($buf, 1);
                        $this->putPacket($player, $pk, false, $immediate);
                    }
                    break;
            }
            if($needACK){
                $id = count($this->ackStore[$player->getName()]);
                $this->ackStore[$player->getName()][] = $id;
                $this->specter->getLogger()->info("Created ACK.");
                return $id;
            }
        }
        return null;
    }

    /**
     * Terminates the connection
     *
     * @param Player $player
     * @param string $reason
     *
     */
    public function close(Player $player, string $reason = "unknown reason"){
        $this->sessions->detach($player);
        unset($this->ackStore[$player->getName()]);
        unset($this->replyStore[$player->getName()]);
    }

    /**
     * @param string $name
     */
    public function setName(string $name){
        // TODO: Implement setName() method.
    }
    public function openSession($username, $address = "SPECTER", $port = 19133){
        if(!isset($this->replyStore[$username])) {
            $player = new SpecterPlayer($this, null, $address, $port);
            $this->sessions->attach($player, $username);
            $this->ackStore[$username] = [];
            $this->replyStore[$username] = [];
            $this->specter->getServer()->addPlayer($username, $player);

            $pk = new class() extends LoginPacket{
                public function decodeAdditional(){
                }
            };
            $pk->username = $username;
            $pk->protocol = ProtocolInfo::CURRENT_PROTOCOL;
            $pk->clientUUID = UUID::fromData($address, $port, $username)->toString();
            $pk->clientId = 1;
            $pk->identityPublicKey = "key here";

			$pk->clientData["SkinId"] = "YzE4ZTY1YWEtN2IyMS00NjM3LTliNjMtOGFkNjM2MjJlZjAxX0FsZXg=";
			$pk->clientData["SkinData"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADlmUf/5ZlH/+WNP//lmUf/5ZlH/+WNP//lmUf/5Y0//9iAMv/YgDL/2IAy/9iAMv/YgDL/2IAy/9iAMv/YgDL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN+ZTADfmUwA34xFAN+ZTADfmUwA34xFAN+ZTADfjEUA0X84ANF/OADRfzgA0X84ANF/OADRfzgA0X84ANF/OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5Y0//+WZR//ljT//5ZlH/+WZR//ckzz/5ZlH/+idTP/YgDL/2IAy/6qJXv+qiV7/qole/6qJXv/YgDL/2IAy/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADfjEUA35lMAN+MRQDfmUwA35lMANaSQQDfmUwA4p1SANF/OADRfzgAp4lhAKeJYQCniWEAp4lhANF/OADRfzgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOWZR//ckzz/6J1M/+WZR//ljT//3JM8/+WNP//lmUf/2IAy/6qJXv+ce1D/nHtQ/5x7UP+ce1D/qole/9iAMv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA35lMANaSQQDinVIA35lMAN+MRQDWkkEA34xFAN+ZTADRfzgAp4lhAJl6UgCZelIAmXpSAJl6UgCniWEA0X84AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADljT//3JM8/+idTP/lmUf/5ZlH/+WZR//ljT//3JM8/9iAMv+qiV7/nHtQ/5x7UP+ce1D/nHtQ/6qJXv/YgDL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN+MRQDWkkEA4p1SAN+ZTADfmUwA35lMAN+MRQDWkkEA0X84AKeJYQCZelIAmXpSAJl6UgCZelIAp4lhANF/OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5Y0//+WNP//onUz/5Y0//+WZR//ljT//6J1M/9yTPP/fxqP/qole/5x7UP+ce1D/nHtQ/5x7UP+qiV7/2IAy/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADfjEUA34xFAOKdUgDfjEUA35lMAN+MRQDinVIA1pJBAN3FpACniWEAmXpSAJl6UgCZelIAmXpSAKeJYQDRfzgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOWZR//ljT//5ZlH/+WNP//ckzz/5ZlH/+idTP/onUz/38aj/6qJXv+ce1D/nHtQ/5x7UP+ce1D/qole/9iAMv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA35lMAN+MRQDfmUwA34xFANaSQQDfmUwA4p1SAOKdUgDdxaQAp4lhAJl6UgCZelIAmXpSAJl6UgCniWEA0X84AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADckzz/5Y0//+WNP//lmUf/5ZlH/+WZR//ljT//6J1M/9/Go/+qiV7/qole/6qJXv+qiV7/qole/6qJXv/YgDL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANaSQQDfjEUA34xFAN+ZTADfmUwA35lMAN+MRQDinVIA3cWkAKeJYQCniWEAp4lhAKeJYQCniWEAp4lhANF/OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6J1M/+WZR//ljT//6J1M/+idTP/ljT//6J1M/9yTPP/fxqP/38aj/9/Go//fxqP/38aj/9/Go//fxqP/38aj/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADinVIA35lMAN+MRQDinVIA4p1SAN+MRQDinVIA1pJBAN3FpADdxaQA3cWkAN3FpADdxaQA3cWkAN3FpADdxaQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADlmUf/5Y0//+idTP/lmUf/6J1M/+idTP/onUz/5Y0//+WZR//ljT//5ZlH/+WNP//ljT//5ZlH/+WNP//lmUf/5ZlH/+WNP//lmUf/5Y0//+WZR//ljT//6J1M/+WZR//ljT//5ZlH/+WNP//lmUf/5Y0//+WZR//onUz/5Y0//9+ZTADfjEUA4p1SAN+ZTADinVIA4p1SAOKdUgDfjEUA35lMAN+MRQDfmUwA34xFAN+MRQDfmUwA34xFAN+ZTADfmUwA34xFAN+ZTADfjEUA35lMAN+MRQDinVIA35lMAN+MRQDfmUwA34xFAN+ZTADfjEUA35lMAOKdUgDfjEUA5Y0//+WZR//lmUf/5Y0//+WZR//ljT//5Y0//+WZR//ljT//5ZlH/+WNP//lmUf/3JM8/+WZR//lmUf/5Y0//+WZR//onUz/6J1M/+idTP/ljT//5ZlH/+WNP//lmUf/6J1M/+idTP/lmUf/5Y0//+idTP/onUz/5Y0//+WZR//fjEUA35lMAN+ZTADfjEUA35lMAN+MRQDfjEUA35lMAN+MRQDfmUwA34xFAN+ZTADWkkEA35lMAN+ZTADfjEUA35lMAOKdUgDinVIA4p1SAN+MRQDfmUwA34xFAN+ZTADinVIA4p1SAN+ZTADfjEUA4p1SAOKdUgDfjEUA35lMAOidTP/onUz/5Y0//+WZR//ljT//5ZlH/+idTP/lmUf/5ZlH/+WNP//lmUf/3JM8/+vTs//r07P/5ZlH/+WNP//onUz/5Y0//+WNP//ljT//6J1M/+WZR//ljT//6J1M/+idTP/onUz/5Y0//+idTP/lmUf/6J1M/+WNP//lmUf/4p1SAOKdUgDfjEUA35lMAN+MRQDfmUwA4p1SAN+ZTADfmUwA34xFAN+ZTADWkkEA6dK1AOnStQDfmUwA34xFAOKdUgDfjEUA34xFAN+MRQDinVIA35lMAN+MRQDinVIA4p1SAOKdUgDfjEUA4p1SAN+ZTADinVIA34xFAN+ZTADlmUf/3JM8/+WZR//lmUf/6J1M/9yTPP/ckzz/5ZlH/9yTPP/ckzz/3JM8/+vTs//y2rr/5Mup/+TLqf/lmUf/5ZlH/+WZR//ckzz/5ZlH/+WNP//onUz/6J1M/+WZR//ljT//6J1M/+WNP//onUz/5ZlH/+WNP//lmUf/5Y0//9+ZTADWkkEA35lMAN+ZTAAAAAAAAAAAAAAAAADfmUwAAAAAAAAAAAAAAAAA6dK1APDZvAAAAAAAAAAAAAAAAADfmUwAAAAAAAAAAAAAAAAA34xFAOKdUgDinVIA35lMAN+MRQDinVIA34xFAOKdUgDfmUwA34xFAN+ZTADfjEUA3JM8/+WZR//lmUf/5ZlH/9yTPP/r07P/69Oz/9yTPP/ky6n/+/v7/yNiJP/y2rr/8t3C/yNiJP/7+/v/5Mup/9yTPP/ljT//5ZlH/+WZR//lmUf/5Y0//+WZR//ljT//5ZlH/+WNP//lmUf/5ZlH/+idTP/lmUf/5ZlH/+idTP/WkkEA35lMAN+ZTADfmUwAAAAAAOnStQDp0rUAAAAAAHNKHAD7+/sANXs2AAAAAAAAAAAANXs2APv7+wBzShwAAAAAAN+MRQDfmUwAAAAAAN+ZTADfjEUA35lMAN+MRQDfmUwA34xFAN+ZTADfmUwA4p1SAN+ZTADfmUwA4p1SANyTPP/ljT//6J1M/9yTPP/r07P/8t3C//Lauv/y2rr/7ta2/+/Zu//y2rr/8t3C//Lauv/y273/7te5//Lauv/r07P/3JM8/+WZR//ljT//5ZlH/+WZR//onUz/5Y0//+WNP//onUz/5ZlH/+WNP//ljT//6J1M/+WZR//lmUf/1pJBAN+MRQDinVIA1pJBAOnStQDw3MMA8Nm8APDZvAAAAAAAAAAAAAAAAADw3MMA8Nm8AAAAAAAAAAAAAAAAAOnStQDWkkEA35lMAN+MRQDfmUwA35lMAOKdUgDfjEUA34xFAOKdUgDfmUwA34xFAN+MRQDinVIA35lMAN+ZTADljT//5ZlH/+idTP/lmUf/69Oz//Lauv/y3cL/8t3C//Lauv/y3cL/8tq6/++7sf/vu7H/8tq6//Lauv/r07P/8t3C/+vTs//ckzz/5Y0//+WZR//ljT//5ZlH/+idTP/ljT//5Y0//+WNP//lmUf/6J1M/+WZR//lmUf/5Y0//9+MRQDfmUwA4p1SAN+ZTADp0rUA8Nm8APDcwwDw3MMA8Nm8APDcwwDw2bwA7b2zAO29swDw2bwA8Nm8AOnStQDw3MMA6dK1ANaSQQDfjEUA35lMAN+MRQDfmUwA4p1SAN+MRQDfjEUA34xFAN+ZTADinVIA35lMAN+ZTADfjEUA5ZlH/+WNP//lmUf/69Oz/+vTs//y3cL/8tq6//Lauv/y2rr/8tq6//Ldwv/y2rr/8tq6//Ldwv/y3cL/8tq6/+vTs//ckzz/5Y0//+WZR//lmUf/5Y0//+WZR//ljT//5ZlH/+WNP//onUz/5ZlH/+WZR//ckzz/5Y0//+idTP/fmUwA34xFAN+ZTADp0rUA6dK1APDcwwDw2bwA8Nm8APDZvADw2bwA8NzDAPDZvADw2bwA8NzDAPDcwwDw2bwA6dK1ANaSQQDfjEUA35lMAN+ZTADfjEUA35lMAN+MRQDfmUwA34xFAOKdUgDfmUwA35lMANaSQQDfjEUA4p1SAAAAAAAAAAAAAAAAAAAAAABkQSz/ZEEs/2RBLP9kQSz/KCgo/ygoKP8oKCj/KCgo/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAerV3/4aHYf/YgDL/2IAy/9iAMv/YgDL/6J1M/+WZR/9oRTD/aEUw/2hFMP9oRTD/aEUw/2hFMP9oRTD/aEUw/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeq93/3qvd/96r3f/2LqU/+vTs//YupT/UTElAFExJQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZEEs/2RBLP9kQSz/ZEEs/ygoKP8oKCj/KCgo/ygoKP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHq1d/+Gh2H/hodh/4aHYf+Gh2H/2IAy/+WZR//onUz/aEUw/2hFMP9oRTD/aEUw/2hFMP9oRTD/aEUw/2hFMP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHqvd/96tXf/eq93/9i6lP/r07P/2LqU/1ExJQBRMSUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGRBLP9kQSz/ZEEs/2RBLP8oKCj/KCgo/ygoKP8oKCj/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB6tXf/hodh/4aHYf/fxqP/38aj/4aHYf/lmUf/6J1M/2hFMP9oRTD/aEUw/2hFMP9oRTD/aEUw/2hFMP9oRTD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB6r3f/erV3/3qvd//r07P/2LqU/+vTs/9qQDAAakAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkQSz/ZEEs/2RBLP9kQSz/KCgo/ygoKP8oKCj/KCgo/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAerV3/4aHYf/r07P/8tq6//Lauv/lmUf/5ZlH/+WNP/9oRTD/aEUw/2hFMP9oRTD/aEUw/2hFMP9oRTD/aEUw/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeq93/3qvd/96r3f/69Oz/9i6lP/r07P/akAwAGpAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB6r3f/erV3/3q1d/96r3f/aEUw/3lVPf+AWkD/bUoz/2hFMP9kQSz/aEUw/2RBLP+Mvor/jL6K/32yev99snr/erV3/3q1d/96tXf/eq93/4y+iv+Gh2H/69Oz//Lauv/y2rr/6J1M/+idTP/ljT//6J1M/+idTP/lmUf/6J1M/+idTP/onUz/5ZlH/+WNP//lmUf/5ZlH/4G1f/+Luoj/eq93/3q1d/96r3f/eq93/4y+iv+Luoj/fbJ6/3qvd/96tXf/erV3/3qvd/+Luoj/jL6K/4u6iP8Ar68AAK+vAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZEEs/3qvd/96r3f/aEUw/3JONv95VT3/eVU9/2hFMP9kQSz/aEUw/2hFMP9kQSz/b0w1/4BaQP+AWkD/ck42/3q1d/96tXf/eq93/3qvd/+Mvor/iotm/+vTs//y2rr/8tq6//Lauv/lmUf/6J1M/+WZR//lmUf/eq93/3qvd//lmUf/5Y0//+WNP//lmUf/gbV//4G1f/+Luoj/i7qI/3qvd/96r3f/eq93/3q1d/+Luoj/fbJ6/4y+iv96tXf/erV3/3qvd/96r3f/i7qI/4u6iP+Mvor/AK+vAACvrwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGRBLP9oRTD/ZEEs/2hFMP9vTDX/gFpA/2hFMP9yTjb/ZEEs/2hFMP9kQSz/aEUw/29MNf+AWkD/eVU9/3JONv96r3f/erV3/3qvd/96r3f/jL6K/32yev+MjWj/69Oz/+vTs//ljT//5ZlH/+idTP96r3f/eq93/3qvd/96tXf/gbV//4G1f/+BtX//gbV//4y+iv+Luoj/i7qI/4u6iP96r3f/erV3/3q1d/96tXf/i7qI/4y+iv+Luoj/eq93/3q1d/96tXf/eq93/4y+iv+Luoj/jL6K/wCvrwAAr68AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkQSz/ZEEs/2RBLP9oRTD/aEUw/2hFMP95VT3/ck42/2RBLP9oRTD/ZEEs/2hFMP9vTDX/gFpA/3lVPf9yTjb/eq93/3q1d/96r3f/eq93/3evdf+Mvor/jL6K/4yNaP+MjWj/5ZlH/+idTP99snr/erV3/3q1d/96r3f/erV3/4y+iv+Luoj/jL6K/4u6iP+Luoj/i7qI/32yev+Luoj/gIJa/4eJYv+HiWL/gIJa/4aHYf+PkGv/hodh/4CCWv+HiWL/h4li/4CCWv+Gh2H/j5Br/4aHYf8Ar68AAK+vAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZEEs/2RBLP9kQSz/ZEEs/29MNf+GXkb/hl5G/29MNf9kQSz/ZEEs/2RBLP9kQSz/aEUw/2hFMP9oRTD/aEUw/3qvd/96tXf/erV3/3q1d/93r3X/jL6K/4y+iv99snr/jL6K/+idTP99tHr/i7qI/3qvd/96r3f/eq93/3q1d/+Mvor/i7qI/4y+iv+Luoj/i7qI/4y+iv+Mvor/jL6K/+TJqP/kyaj/5Mmo/+TJqP/r07P/69Oz/+vTs//kyaj/5Mmo/+TJqP/kyaj/69Oz/+vTs//r07P/qn1mAKp9ZgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADs7O/87Ozv/Ozs7/2RBLP9oRTD/eFQ8/3hUPP9oRTD/ZEEs/zs7O/87Ozv/Ozs7/0ZGRv9GRkb/RkZG/0ZGRv96r3f/erV3/3qvd/96tXf/fbJ6/4y+iv+Luoj/jL6K/4u6iP+Mvor/i7qI/4u6iP96r3f/eq93/3qvd/96r3f/i7qI/32yev+Mvor/i7qI/4u6iP+Mvor/i7qI/4y+iv/kyaj/5Mmo/+vTs//r07P/8tq6//Lauv/r07P/69Oz/+vTs//kyaj/69Oz//Lauv/r07P/8tq6/6p9ZgCqfWYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABJSUn/SUlJ/0lJSf87Ozv/Wlpa/11dXf9dXV3/Wlpa/zs7O/9JSUn/SUlJ/0lJSf9NTU3/V1dX/1dXV/9NTU3/eq93/3q1d/96r3f/erV3/4y+iv+Mvor/fbJ6/4y+iv+Luoj/jL6K/4u6iP+Mvor/eq93/3q1d/96r3f/eq93/4u6iP+Mvor/jL6K/4u6iP+Mvor/fbJ6/4y+iv+Mvor/5Mmo/+vTs//r07P/69Oz//Lauv/y2rr/6dCv/+vTs//s1Lj/5Muq/+zUuP/y2rr/8tq6//Ldwv+qfWYAqn1mAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASUlJ/0lJSf9JSUn/SUlJ/2FhYf9ra2v/a2tr/2FhYf9JSUn/SUlJ/0lJSf9JSUn/TU1N/1dXV/9XV1f/TU1N/3q1d/96tXf/erV3/3q1d/+Mvor/jL6K/3evdf+Mvor/fbJ6/4y+iv+Mvor/jL6K/3qvd/96tXf/erV3/3q1d/+Mvor/jL6K/4y+iv99snr/jL6K/32yev+Mvor/jL6K/+zUuP/r07P/7NS4/+vTs//p0bP/8tq6//Lauv/v2b3/7NS4/+XLrf/v2r//8tq6//Lauv/p0bP/qn1mAKp9ZgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAElJSf9JSUn/Ozs7/0lJSf9hYWH/a2tr/2tra/9hYWH/SUlJ/zs7O/9JSUn/SUlJ/01NTf9XV1f/V1dX/01NTf8YOBb/Gj8Z/xg4Fv8aPxn/T4BM/4y+iv93r3X/jL6K/3evdf+Mvor/jL6K/0+ATP8aPxn/Gj8Z/xg4Fv8aPxn/T4BM/4y+iv+Mvor/d7B0/4y+iv93r3X/jL6K/0+ATP/s1Lj/7NS4/+zUuP/s1Lj/6dGz//Ldwv/y3cL/7NS4/+/av//s1Lj/7NS4//Ldwv/y3cL/8t3C/6p9ZgCqfWYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABNTU3/TU1N/1JSUv87Ozv/Wlpa/2NjY/9jY2P/Wlpa/zs7O/9SUlL/TU1N/01NTf9KSkr/UFBQ/1BQUP9KSkr/erV3/3qvd/96tXf/eq93/xg4Fv8YOBb/GDgW/xo/Gf8aPxn/GDgW/xg4Fv8aPxn/eq93/3qvd/96tXf/erV3/xo/Gf8YOBb/GDgW/xo/Gf8aPxn/GDgW/xo/Gf8aPxn/7NS4/+zUuP/v2r//79q///Ldwv/y3cL/8t/I/+zUuP/v2r//7NS4/+zUuP/y38j/8t3C/+rUuP+Wb1sAlm9bAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATU1N/01NTf9SUlL/XFxc/2FhYf9ra2v/a2tr/2FhYf9cXFz/UlJS/01NTf9NTU3/SkpK/1BQUP9QUFD/SkpK/3q1d/96r3f/erV3/3qvd/+Luoj/jL6K/4u6iP+Mvor/fbJ6/4u6iP+Luoj/jL6K/3qvd/96r3f/erV3/3qvd/+Luoj/jL6K/4y+iv99snr/jL6K/4u6iP+Luoj/jL6K/+/av//v2r//7NS4/+/av//y38j/8t/I//Ldwv/v2r//79q//+/av//s1Lj/8t/I//Ldwv/y3cL/lm9bAJZvWwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8/P/8/Pz//Pz8//1xcXP9jY2P/cHBw/3BwcP9jY2P/XFxc/z8/P/8/Pz//Pz8//0hISP9MTEz/TExM/0hISP96r3f/erV3/3q1d/96r3f/i7qI/2hFMP91UDj/dVA4/3VQOP91UDj/aEUw/4u6iP96tXf/eq93/3q1d/96r3f/i7qI/4y+iv+Mvor/jL6K/4y+iv+Mvor/jL6K/4u6iP/s1Lj/79m9/+zUuP/v2r//8t/I//Ldwv/y3cL/7NS4/+zUuP/v2r//7NS4//LfyP/y3cL/8t3C/5ZvWwCWb1sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABlZWUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMjAAAqqoAAIyMAGpAMABRMSUAUTElAFExJQBRMSUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqqoAAMzMAACqqgBqQDAAakAwAFExJQBRMSUAUTElAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKqqAADMzAAAjIwAUTElAFExJQBqQDAAakAwAGpAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMjAAAqqoAAIyMAFExJQBqQDAAakAwAGpAMABqQDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABeXgAAamoAAGpqAABqagAAhIQAAIyMAACMjAAAamoAAGpqAABqagAAamoAAJKSAACSkgAAenoAAHp6AAB6egAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAS0sAAGhoAABoaAAAf38AAK+vAACoqAAAnp4AAH9/AAB/fwAAaGgAAH9/AACvrwAAr68AAJKSAACSkgAAkpIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF5eAABoaAAAaGgAAH9/AACoqAAAr68AAK+vAAB/fwAAf38AAGhoAAB/fwAAr68AAK+vAACSkgAAkpIAAJKSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABeXgAAaGgAAGhoAAB/fwAAnp4AAK+vAACengAAf38AAH9/AABoaAAAf38AAK+vAACvrwAAkpIAAJKSAACSkgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAByRCsAll9BAJZfQQCHVTsAqn1mAKp9ZgCqfWYAh1U7AIdVOwCWX0EAll9BAKp9ZgCqfWYAjmhVAI5oVQCOaFUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAckQrAJZfQQCWX0EAh1U7AKp9ZgCWb1sAqn1mAJZfQQCWX0EAh1U7AJZfQQCqfWYAqn1mAI5oVQCOaFUAjmhVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGU7JgCWX0EAll9BAIdVOwCqfWYAlm9bAJZvWwCWX0EAll9BAIdVOwCWX0EAqn1mAKp9ZgCOaFUAjmhVAI5oVQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABlOyYAll9BAJZfQQCWX0EAqn1mAKp9ZgCWb1sAll9BAJZfQQCHVTsAh1U7AKp9ZgCqfWYAjmhVAI5oVQCOaFUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZTsmAJZfQQCHVTsAll9BAKp9ZgCqfWYAlm9bAJZfQQCWX0EAll9BAIdVOwCqfWYAqn1mAI5oVQCOaFUAjmhVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHJEKwCWX0EAh1U7AJZfQQCqfWYAqn1mAKp9ZgCWX0EAll9BAJZfQQCWX0EAqn1mAKp9ZgB9XUwAfV1MAH1dTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAByRCsAll9BAIdVOwCWX0EAqn1mAKp9ZgCqfWYAh1U7AIdVOwCWX0EAll9BAKp9ZgCqfWYAfV1MAH1dTAB9XUwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAckQrAJZfQQCWX0EAll9BAH1dTACOaFUAfV1MAHFHMQB9TzYAfU82AH1PNgCOaFUAfV1MAH1dTAB9XUwAfV1MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkQSz/ZEEs/2RBLP9kQSz/KCgo/ygoKP8oKCj/KCgo/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6J1M/3q1d/96r3f/2LqU/+vTs//YupT/akAwAGpAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMjAAAqqoAAKqqAGpAMABRMSUAUTElAFExJQBRMSUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZEEs/2RBLP9kQSz/ZEEs/ygoKP8oKCj/KCgo/ygoKP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOWZR//onUz/eq93/9i6lP/r07P/2LqU/2pAMABqQDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqqoAAAAAAACMjABqQDAAakAwAFExJQBRMSUAUTElAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGRBLP9kQSz/ZEEs/2RBLP8oKCj/KCgo/ygoKP8oKCj/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADlmUf/5Y0//3qvd//r07P/2LqU/+vTs/9RMSUAUTElAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKqqAAAAAAAAqqoAUTElAFExJQBqQDAAakAwAGpAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkQSz/ZEEs/2RBLP9kQSz/KCgo/ygoKP8oKCj/KCgo/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5Y0//3q1d/96r3f/69Oz/9i6lP/r07P/UTElAFExJQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMjAAAqqoAAIyMAFExJQBqQDAAakAwAGpAMABqQDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABoRTD/ZEEs/2hFMP9kQSz/bUoz/4BaQP95VT3/aEUw/2hFMP9kQSz/aEUw/2RBLP9vTDX/fbJ6/4y+iv+Mvor/eq93/3q1d/96r3f/5ZlH/+WNP/+Luoj/i7qI/3qvd/96r3f/eq93/3qvd/+Luoj/jL6K/+WNP/8Ar68AAK+vAABeXgAAamoAAGpqAABqagAAhIQAAIyMAACMjAAAamoAAGpqAABqagAAamoAAJKSAACSkgAAenoAAHp6AAB6egAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZEEs/2hFMP9kQSz/aEUw/2hFMP95VT3/eVU9/3JONv9kQSz/aEUw/2hFMP9kQSz/b0w1/4BaQP+AWkD/ck42/3qvd/96r3f/eq93/+idTP/lmUf/i7qI/4u6iP96r3f/erV3/3qvd/96r3f/i7qI/4u6iP+Mvor/AK+vAACvrwAAS0sAAAAAAAAAAAAAf38AAK+vAAAAAAAAjIwAAH9/AAB/fwAAAAAAAH9/AACvrwAAr68AAJKSAACSkgAAkpIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGRBLP9oRTD/ZEEs/2hFMP9yTjb/aEUw/4BaQP9vTDX/ZEEs/2hFMP9kQSz/aEUw/29MNf+AWkD/eVU9/3JONv96r3f/erV3/3q1d/96tXf/i7qI/4y+iv99snr/eq93/3q1d/96tXf/eq93/4y+iv+Luoj/jL6K/wCvrwAAr68AAF5eAAAAAAAAAAAAAH9/AACoqAAAAAAAAJ6eAAB/fwAAf38AAAAAAAB/fwAAr68AAK+vAACSkgAAkpIAAJKSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkQSz/ZEEs/2RBLP9oRTD/ck42/3lVPf9oRTD/aEUw/2RBLP9oRTD/ZEEs/2hFMP9vTDX/gFpA/3lVPf9yTjb/gIJa/4eJYv+HiWL/gIJa/4aHYf+PkGv/hodh/4CCWv+HiWL/h4li/4CCWv+Gh2H/j5Br/4aHYf8Ar68AAK+vAABeXgAAAAAAAAAAAAB/fwAAnp4AAAAAAACvrwAAf38AAH9/AAAAAAAAf38AAK+vAACvrwAAkpIAAJKSAACSkgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZEEs/2RBLP9kQSz/ZEEs/29MNf+GXkb/hl5G/29MNf9kQSz/ZEEs/2RBLP9kQSz/aEUw/2hFMP9oRTD/aEUw/+TJqP/kyaj/5Mmo/+TJqP/r07P/69Oz/+vTs//kyaj/5Mmo/+TJqP/kyaj/69Oz/+vTs//r07P/qn1mAKp9ZgByRCsAAAAAAAAAAACHVTsAqn1mAAAAAAAAnp4Ah1U7AIdVOwAAAAAAll9BAKp9ZgCqfWYAjmhVAI5oVQCOaFUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADs7O/87Ozv/Ozs7/2RBLP9oRTD/eFQ8/3hUPP9oRTD/ZEEs/zs7O/87Ozv/Ozs7/0ZGRv9GRkb/RkZG/0ZGRv/kyaj/5Mmo/+vTs//r07P/8tq6//Lauv/r07P/69Oz/+vTs//kyaj/69Oz//Lauv/r07P/8tq6/6p9ZgCqfWYAckQrAAAAAAAAAAAAh1U7AKp9ZgAAAAAAqn1mAJZfQQCWX0EAAAAAAJZfQQCqfWYAqn1mAI5oVQCOaFUAjmhVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABJSUn/SUlJ/0lJSf87Ozv/Wlpa/11dXf9dXV3/Wlpa/zs7O/9JSUn/SUlJ/0lJSf9NTU3/V1dX/1dXV/9NTU3/5Mmo/+vTs//r07P/69Oz//Lauv/y2rr/8tq6/+vTs//s1Lj/69Oz/+zUuP/y2rr/8tq6//Ldwv+qfWYAqn1mAGU7JgAAAAAAAAAAAIdVOwCqfWYAAAAAAKp9ZgCWX0EAll9BAAAAAACWX0EAqn1mAKp9ZgCOaFUAjmhVAI5oVQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASUlJ/0lJSf9JSUn/SUlJ/2FhYf9ra2v/a2tr/2FhYf9JSUn/SUlJ/0lJSf9JSUn/TU1N/1dXV/9XV1f/TU1N/+zUuP/r07P/7NS4/+/Zvf/p0bP/8tq6//Lauv/r07P/7NS4/+XLrf/s1Lj/8tq6//Lauv/y3cL/qn1mAKp9ZgDi164A7ebJAO3myQDi164A5NuzAPHs0QDk27MA4teuAOTbswDk27MA4teuAOTbswDx7NEA5NuzAI5oVQCOaFUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAElJSf9JSUn/Ozs7/0lJSf9hYWH/a2tr/2tra/9hYWH/SUlJ/zs7O/9JSUn/SUlJ/01NTf9XV1f/V1dX/01NTf/s1Lj/7NS4/+zUuP/s1Lj/6dGz//Ldwv/y3cL/7NS4/+zUuP/s1Lj/7NS4/+nRs//y3cL/8t3C/6p9ZgCqfWYAZTsmAAAAAAAAAAAAll9BAKp9ZgAAAAAAlm9bAJZfQQCWX0EAAAAAAIdVOwCqfWYAqn1mAI5oVQCOaFUAjmhVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABNTU3/TU1N/1JSUv87Ozv/Wlpa/2NjY/9jY2P/Wlpa/zs7O/9SUlL/TU1N/01NTf9KSkr/UFBQ/1BQUP9KSkr/7NS4/+zUuP/v2r//7NS4//Ldwv/y3cL/6dGz/+zUuP/s1Lj/79q//+zUuP/y3cL/8t3C//Ldwv+qfWYAqn1mAOLXrgDk27MA5NuzAOLXrgDk27MA8ezRAOTbswDi164A5NuzAOTbswDi164A5NuzAPHs0QDk27MAfV1MAH1dTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATU1N/01NTf9SUlL/XFxc/2FhYf9ra2v/a2tr/2FhYf9cXFz/UlJS/01NTf9NTU3/SkpK/1BQUP9QUFD/SkpK/+/av//s1Lj/79q//+zUuP/y3cL/8t/I//Ldwv/v2r//7NS4/+zUuP/v2r//8t3C//LfyP/y38j/qn1mAKp9ZgByRCsAAAAAAAAAAACWX0EAqn1mAAAAAACqfWYAh1U7AIdVOwAAAAAAll9BAKp9ZgCqfWYAfV1MAH1dTAB9XUwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8/P/8/Pz//Pz8//1xcXP9jY2P/cHBw/3BwcP9jY2P/XFxc/z8/P/8/Pz//Pz8//0hISP9MTEz/TExM/0hISP/v2r//69Oz/+zUuP/s1Lj/8t/I//Ldwv/y3cL/7NS4/+/av//s1Lj/7NS4//Ldwv/y38j/8t/I/6p9ZgCqfWYAckQrAJZfQQCWX0EAll9BAH1dTACOaFUAqn1mAHFHMQB9TzYAfU82AH1PNgCOaFUAfV1MAH1dTAB9XUwAfV1MAA==";
			$pk->clientData["CapeData"] = null;
			$pk->clientData["SkinGeometryName"] = "Z2VvbWV0cnkuaHVtYW5vaWQuY3VzdG9tU2xpbQ==";
			$pk->clientData["SkinGeometry"] = "eyJnZW9tZXRyeS5odW1hbm9pZCI6eyJib25lcyI6W3sibmFtZSI6ImJvZHkiLCJwaXZvdCI6WzAsMjQsMF0sImN1YmVzIjpbeyJvcmlnaW4iOlstNCwxMiwtMl0sInNpemUiOls4LDEyLDRdLCJ1diI6WzE2LDE2XX1dfSx7Im5hbWUiOiJ3YWlzdCIsIm5ldmVyUmVuZGVyIjp0cnVlLCJwaXZvdCI6WzAsMTIsMF19LHsibmFtZSI6ImhlYWQiLCJwaXZvdCI6WzAsMjQsMF0sImN1YmVzIjpbeyJvcmlnaW4iOlstNCwyNCwtNF0sInNpemUiOls4LDgsOF0sInV2IjpbMCwwXX1dfSx7Im5hbWUiOiJoYXQiLCJwaXZvdCI6WzAsMjQsMF0sImN1YmVzIjpbeyJvcmlnaW4iOlstNCwyNCwtNF0sInNpemUiOls4LDgsOF0sInV2IjpbMzIsMF0sImluZmxhdGUiOjAuNX1dLCJuZXZlclJlbmRlciI6dHJ1ZX0seyJuYW1lIjoicmlnaHRBcm0iLCJwaXZvdCI6Wy01LDIyLDBdLCJjdWJlcyI6W3sib3JpZ2luIjpbLTgsMTIsLTJdLCJzaXplIjpbNCwxMiw0XSwidXYiOls0MCwxNl19XX0seyJuYW1lIjoibGVmdEFybSIsInBpdm90IjpbNSwyMiwwXSwiY3ViZXMiOlt7Im9yaWdpbiI6WzQsMTIsLTJdLCJzaXplIjpbNCwxMiw0XSwidXYiOls0MCwxNl19XSwibWlycm9yIjp0cnVlfSx7Im5hbWUiOiJyaWdodExlZyIsInBpdm90IjpbLTEuOSwxMiwwXSwiY3ViZXMiOlt7Im9yaWdpbiI6Wy0zLjksMCwtMl0sInNpemUiOls0LDEyLDRdLCJ1diI6WzAsMTZdfV19LHsibmFtZSI6ImxlZnRMZWciLCJwaXZvdCI6WzEuOSwxMiwwXSwiY3ViZXMiOlt7Im9yaWdpbiI6Wy0wLjEsMCwtMl0sInNpemUiOls0LDEyLDRdLCJ1diI6WzAsMTZdfV0sIm1pcnJvciI6dHJ1ZX1dfSwiZ2VvbWV0cnkuY2FwZSI6eyJ0ZXh0dXJld2lkdGgiOjY0LCJ0ZXh0dXJlaGVpZ2h0IjozMiwiYm9uZXMiOlt7Im5hbWUiOiJjYXBlIiwicGl2b3QiOlswLDI0LC0zXSwiY3ViZXMiOlt7Im9yaWdpbiI6Wy01LDgsLTNdLCJzaXplIjpbMTAsMTYsMV0sInV2IjpbMCwwXX1dLCJtYXRlcmlhbCI6ImFscGhhIn1dfSwiZ2VvbWV0cnkuaHVtYW5vaWQuY3VzdG9tOmdlb21ldHJ5Lmh1bWFub2lkIjp7ImJvbmVzIjpbeyJuYW1lIjoiaGF0IiwibmV2ZXJSZW5kZXIiOmZhbHNlLCJtYXRlcmlhbCI6ImFscGhhIiwicGl2b3QiOlswLDI0LDBdfSx7Im5hbWUiOiJsZWZ0QXJtIiwicmVzZXQiOnRydWUsIm1pcnJvciI6ZmFsc2UsInBpdm90IjpbNSwyMiwwXSwiY3ViZXMiOlt7Im9yaWdpbiI6WzQsMTIsLTJdLCJzaXplIjpbNCwxMiw0XSwidXYiOlszMiw0OF19XX0seyJuYW1lIjoicmlnaHRBcm0iLCJyZXNldCI6dHJ1ZSwicGl2b3QiOlstNSwyMiwwXSwiY3ViZXMiOlt7Im9yaWdpbiI6Wy04LDEyLC0yXSwic2l6ZSI6WzQsMTIsNF0sInV2IjpbNDAsMTZdfV19LHsibmFtZSI6InJpZ2h0SXRlbSIsInBpdm90IjpbLTYsMTUsMV0sIm5ldmVyUmVuZGVyIjp0cnVlLCJwYXJlbnQiOiJyaWdodEFybSJ9LHsibmFtZSI6ImxlZnRTbGVldmUiLCJwaXZvdCI6WzUsMjIsMF0sImN1YmVzIjpbeyJvcmlnaW4iOls0LDEyLC0yXSwic2l6ZSI6WzQsMTIsNF0sInV2IjpbNDgsNDhdLCJpbmZsYXRlIjowLjI1fV0sIm1hdGVyaWFsIjoiYWxwaGEifSx7Im5hbWUiOiJyaWdodFNsZWV2ZSIsInBpdm90IjpbLTUsMjIsMF0sImN1YmVzIjpbeyJvcmlnaW4iOlstOCwxMiwtMl0sInNpemUiOls0LDEyLDRdLCJ1diI6WzQwLDMyXSwiaW5mbGF0ZSI6MC4yNX1dLCJtYXRlcmlhbCI6ImFscGhhIn0seyJuYW1lIjoibGVmdExlZyIsInJlc2V0Ijp0cnVlLCJtaXJyb3IiOmZhbHNlLCJwaXZvdCI6WzEuOSwxMiwwXSwiY3ViZXMiOlt7Im9yaWdpbiI6Wy0wLjEsMCwtMl0sInNpemUiOls0LDEyLDRdLCJ1diI6WzE2LDQ4XX1dfSx7Im5hbWUiOiJsZWZ0UGFudHMiLCJwaXZvdCI6WzEuOSwxMiwwXSwiY3ViZXMiOlt7Im9yaWdpbiI6Wy0wLjEsMCwtMl0sInNpemUiOls0LDEyLDRdLCJ1diI6WzAsNDhdLCJpbmZsYXRlIjowLjI1fV0sInBvcyI6WzEuOSwxMiwwXSwibWF0ZXJpYWwiOiJhbHBoYSJ9LHsibmFtZSI6InJpZ2h0UGFudHMiLCJwaXZvdCI6Wy0xLjksMTIsMF0sImN1YmVzIjpbeyJvcmlnaW4iOlstMy45LDAsLTJdLCJzaXplIjpbNCwxMiw0XSwidXYiOlswLDMyXSwiaW5mbGF0ZSI6MC4yNX1dLCJwb3MiOlstMS45LDEyLDBdLCJtYXRlcmlhbCI6ImFscGhhIn0seyJuYW1lIjoiamFja2V0IiwicGl2b3QiOlswLDI0LDBdLCJjdWJlcyI6W3sib3JpZ2luIjpbLTQsMTIsLTJdLCJzaXplIjpbOCwxMiw0XSwidXYiOlsxNiwzMl0sImluZmxhdGUiOjAuMjV9XSwibWF0ZXJpYWwiOiJhbHBoYSJ9XX0sImdlb21ldHJ5Lmh1bWFub2lkLmN1c3RvbVNsaW06Z2VvbWV0cnkuaHVtYW5vaWQiOnsiYm9uZXMiOlt7Im5hbWUiOiJoYXQiLCJuZXZlclJlbmRlciI6ZmFsc2UsIm1hdGVyaWFsIjoiYWxwaGEifSx7Im5hbWUiOiJsZWZ0QXJtIiwicmVzZXQiOnRydWUsIm1pcnJvciI6ZmFsc2UsInBpdm90IjpbNSwyMS41LDBdLCJjdWJlcyI6W3sib3JpZ2luIjpbNCwxMS41LC0yXSwic2l6ZSI6WzMsMTIsNF0sInV2IjpbMzIsNDhdfV19LHsibmFtZSI6InJpZ2h0QXJtIiwicmVzZXQiOnRydWUsInBpdm90IjpbLTUsMjEuNSwwXSwiY3ViZXMiOlt7Im9yaWdpbiI6Wy03LDExLjUsLTJdLCJzaXplIjpbMywxMiw0XSwidXYiOls0MCwxNl19XX0seyJwaXZvdCI6Wy02LDE0LjUsMV0sIm5ldmVyUmVuZGVyIjp0cnVlLCJuYW1lIjoicmlnaHRJdGVtIiwicGFyZW50IjoicmlnaHRBcm0ifSx7Im5hbWUiOiJsZWZ0U2xlZXZlIiwicGl2b3QiOls1LDIxLjUsMF0sImN1YmVzIjpbeyJvcmlnaW4iOls0LDExLjUsLTJdLCJzaXplIjpbMywxMiw0XSwidXYiOls0OCw0OF0sImluZmxhdGUiOjAuMjV9XSwibWF0ZXJpYWwiOiJhbHBoYSJ9LHsibmFtZSI6InJpZ2h0U2xlZXZlIiwicGl2b3QiOlstNSwyMS41LDBdLCJjdWJlcyI6W3sib3JpZ2luIjpbLTcsMTEuNSwtMl0sInNpemUiOlszLDEyLDRdLCJ1diI6WzQwLDMyXSwiaW5mbGF0ZSI6MC4yNX1dLCJtYXRlcmlhbCI6ImFscGhhIn0seyJuYW1lIjoibGVmdExlZyIsInJlc2V0Ijp0cnVlLCJtaXJyb3IiOmZhbHNlLCJwaXZvdCI6WzEuOSwxMiwwXSwiY3ViZXMiOlt7Im9yaWdpbiI6Wy0wLjEsMCwtMl0sInNpemUiOls0LDEyLDRdLCJ1diI6WzE2LDQ4XX1dfSx7Im5hbWUiOiJsZWZ0UGFudHMiLCJwaXZvdCI6WzEuOSwxMiwwXSwiY3ViZXMiOlt7Im9yaWdpbiI6Wy0wLjEsMCwtMl0sInNpemUiOls0LDEyLDRdLCJ1diI6WzAsNDhdLCJpbmZsYXRlIjowLjI1fV0sIm1hdGVyaWFsIjoiYWxwaGEifSx7Im5hbWUiOiJyaWdodFBhbnRzIiwicGl2b3QiOlstMS45LDEyLDBdLCJjdWJlcyI6W3sib3JpZ2luIjpbLTMuOSwwLC0yXSwic2l6ZSI6WzQsMTIsNF0sInV2IjpbMCwzMl0sImluZmxhdGUiOjAuMjV9XSwibWF0ZXJpYWwiOiJhbHBoYSJ9LHsibmFtZSI6ImphY2tldCIsInBpdm90IjpbMCwyNCwwXSwiY3ViZXMiOlt7Im9yaWdpbiI6Wy00LDEyLC0yXSwic2l6ZSI6WzgsMTIsNF0sInV2IjpbMTYsMzJdLCJpbmZsYXRlIjowLjI1fV0sIm1hdGVyaWFsIjoiYWxwaGEifV19fQ==";
            $pk->skipVerification = true;

            $pk->handle($player->getSessionAdapter());

            return true;
        }
        else{
            return false;
        }
    }
    /**
     * @return bool
     */
    public function process() : bool{
        foreach($this->ackStore as $name => $acks){
            $player = $this->specter->getServer()->getPlayer($name);
            if($player instanceof SpecterPlayer){
	            /** @noinspection PhpUnusedLocalVariableInspection */
	            foreach($acks as $id){

	                //$player->handleACK($id); // TODO method removed. Though, Specter shouldn't have ACK to fill.
                    $this->specter->getLogger()->info("Filled ACK.");
                }
            }
            $this->ackStore[$name] = [];
        }
        /**
         * @var string $name
         * @var DataPacket[] $packets
         */
	    foreach($this->replyStore as $name => $packets){
            $player = $this->specter->getServer()->getPlayer($name);
            if($player instanceof SpecterPlayer){
                foreach($packets as $pk){
                    $pk->handle($player->getSessionAdapter());
                }
            }
            $this->replyStore[$name] = [];
        }
        return true;
    }
    public function queueReply(DataPacket $pk, $player){
        $this->replyStore[$player][] = $pk;
    }
    public function shutdown(){
        // TODO: Implement shutdown() method.
    }

    public function emergencyShutdown(){
        // TODO: Implement emergencyShutdown() method.
    }
}
